[package]
name = "swedish_league_back"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
dotenv = "0.15.0"
serde = "1.0.188"
futures = "0.3.28"
tokio = {version = "1.32.0", features = ["full"]}

[dependencies.mongodb]
version = "3.0.1"